development:
  login: 9KSyy53Mh
  password: 6H87q9m7jm4urVRX
production:
  login: 75sqQ96qHEP8
  password: 7r83Sb4HUd58Tz5p
test:
  login: 75sqQ96qHEP8
  password: 7r83Sb4HUd58Tz5p
staging:
  login: 75sqQ96qHEP8
  password: 7r83Sb4HUd58Tz5p
