development:
  login: 's3_1342514477_biz_api1.mailinator.com'
  password: '1342514516'
  signature: 'A5FHW4PF0qmLAT2Q0PVN.Jm-CXeWAwnkxh2QzVjBC5KJrPGzfJMUXhRx'
test:
  login: 's3_1342514477_biz_api1.mailinator.com'
  password: '1342514516'
  signature: 'A5FHW4PF0qmLAT2Q0PVN.Jm-CXeWAwnkxh2QzVjBC5KJrPGzfJMUXhRx'
production:
  login: 's3_1342514477_biz_api1.mailinator.com'
  password: '1342514516'
  signature: 'A5FHW4PF0qmLAT2Q0PVN.Jm-CXeWAwnkxh2QzVjBC5KJrPGzfJMUXhRx'
staging:
  login: 's3_1342514477_biz_api1.mailinator.com'
  password: '1342514516'
  signature: 'A5FHW4PF0qmLAT2Q0PVN.Jm-CXeWAwnkxh2QzVjBC5KJrPGzfJMUXhRx'
