development:
  login: 'gs_1343131071_biz_api1.mailinator.com'
  password: '1343131095'
  signature: 'AYUoXZhCw9z3nmVAUw1vXKz7VtkgArpML7KvjK5HgM2bf69kAOCm403y'
test:
  login: 'gs_1343131071_biz_api1.mailinator.com'
  password: '1343131095'
  signature: 'AYUoXZhCw9z3nmVAUw1vXKz7VtkgArpML7KvjK5HgM2bf69kAOCm403y'
production:
  login: 'gs_1343131071_biz_api1.mailinator.com'
  password: '1343131095'
  signature: 'AYUoXZhCw9z3nmVAUw1vXKz7VtkgArpML7KvjK5HgM2bf69kAOCm403y'
staging:
  login: 'gs_1343131071_biz_api1.mailinator.com'
  password: '1343131095'
  signature: 'AYUoXZhCw9z3nmVAUw1vXKz7VtkgArpML7KvjK5HgM2bf69kAOCm403y'